# Generated by Django 3.0.2 on 2020-01-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='first_name',
            field=models.CharField(default='', max_length=31),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testmodel',
            name='last_name',
            field=models.CharField(default='', max_length=31),
            preserve_default=False,
        ),
    ]
