# Generated by Django 3.0.2 on 2020-06-09 15:13

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_auto_20200116_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
                ('phone', phone_field.models.PhoneField(max_length=31, unique=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.Business')),
            ],
        ),
    ]
